<?php
$escaper = new Zend\Escaper\Escaper('utf-8');
$image_baseurl = "http://akilia2.emdmusic.com/medias/products/dynamic/";
?>


<div class="row" style="margin-top: 5px">	
	<div class="col-md-3">
		<?php
		echo $this->partial('snippets/sidebar_navigation', array(
			'categories' => $this->categories,
			'brands' => $this->brands,
			'searchParams' => $this->searchParams
		))
		?>
	</div>

	<div class="col-md-9">

		<div class="row"">
			<div class="col-md-12">
				<?php $browse_filter = $this->searchParams->getFilter()->getName() ?>
				<ul class="nav nav-tabs pull-right">
					<li <?= ($browse_filter == '' || $browse_filter == 'all') ? 'class="active"' : '' ?>>
						<a href="<?= $this->url('store/browse', array('page' => 1, 'filter' => null)); ?>">All products</a>
					</li>
					<li <?= ($browse_filter == 'promos') ? 'class="active"' : '' ?>>
						<a href="<?= $this->url('store/browse', array('page' => 1, 'filter' => 'promos'), array(), $reuseMatchedParams = true); ?>">Promos</a>	
					</li>
					<li <?= ($browse_filter == 'new') ? 'class="active"' : '' ?>>
						<a href="<?= $this->url('store/browse', array('page' => 1, 'filter' => 'new'), array(), $reuseMatchedParams = true); ?>">New</a>
					</li>
					<li <?= ($browse_filter == 'onstock') ? 'class="active"' : '' ?>>
						<a href="<?= $this->url('store/browse', array('page' => 1, 'filter' => 'onstock'), array(), $reuseMatchedParams = true); ?>">On stock</a>
					</li>			
					<li <?= ($browse_filter == 'favourite') ? 'class="active"' : '' ?>>
						<a href="<?= $this->url('store/browse', array('page' => 1, 'filter' => 'favourites'), array(), $reuseMatchedParams = true); ?>"><span class="glyphicon glyphicon-heart"></span> Favorites</a> 
					</li>
				</ul>
			</div>
		</div>		


		<div class="row"">
			<div class="col-md-12">


				<div class="panel panel-default">
					<div class="panel-body">
						<form class="" action="<?=
						$this->url('store/browse', array(
							'page' => 1,
							'brands' => null,
							'filter' => null,
							'categories' => null,
							'query' => null
								), array(), $reuseMatchedParams = true);
						?>" role="search" onsubmit="openstore_catalog_search()">

							<div class="input-group">

								<input class="form-control" type="text" id="product_search"  name="query" value="<?= $this->searchParams->getQuery() ?>"  placeholder="Search">

								<span class="input-group-btn">
									<button class="btn btn-default" type="button">Go!</button>
								</span>


							</div><!-- /input-group -->		  
						</form>		


					</div>
				</div>		


			</div>
		</div>				

		<?php
		echo $this->partial('snippets/breadcrumb_control', array(
			'category_breadcrumb' => $this->category_breadcrumb,
			'searchParams' => $this->searchParams,
			'brands' => $this->brands
		))
		?>
		<!--<div class="row">	-->
		<?php foreach ($this->products as $idx => $product) : ?>
			<?php
			//echo "<h3>" . $idx % 3 . "</h3>";
			$columns = 3;
			$break = ($idx % $columns) == 0;
			$last_idx = count($this->products);
			?>
			<?php if ($break) : ?>
				<div class="row" > <!-- start row <?php echo "idx" . $idx . " --- ($idx % 3)" ?> -->	
				<?php endif; ?>	
				<div class="col-md-4" style="margin-bottom: 5px">
					<!-- <div class="thumbnail wrapper"> -->
					<div class="thumbnail wrapper" style="background-color: white">

						<div class="ribbon-wrapper-green">
							<div class="ribbon-green"><?= $product->brand_title ?></div>
						</div>
						<div>
							<?php if ($product->promo_discount > 0) : ?>	
								<div class="numbercircle">
									<strong>-<?= number_format($product->promo_discount) ?>%</strong><br />
								</div>
							<?php endif; ?>	

							<div style="padding: 2px 2px;  background: rgba(54, 25, 25, .5); color: white; position: absolute">
								<span><?= $product->reference ?></span>
							</div>	 

							<div style="width: 100%; max-height: 200px; min-height: 80px; line-height: 150px; text-align: center;">

								<a href="<?= $this->url('store/product', array('product_id' => $product['product_id']), array(), false); ?>">
									<img style="vertical-align: middle" src="<?= $image_baseurl . $product->product_id ?>-170x200_90.jpg" alt="" />
								</a>

							</div>

						</div>
						<div class="btn-group" style="float: right">
							<button class="btn btn-sm" onclick="javascript: $.colorbox({maxWidth: '90%', maxHeight: '90%', title: '<?= $escaper->escapeJs((string) $product->brand_title) . ' &raquo; ' . $escaper->escapeJs((string) $product->reference) . ' &raquo; ' . $escaper->escapeJs((string) $product->title) ?>', href: '<?= $image_baseurl . $product->product_id ?>-1024x768_90.jpg?>'})">
								<span class="glyphicon glyphicon-zoom-in"></span> 
							</button>
							<button class="btn btn-sm">
								<span class="glyphicon glyphicon-info-sign"></span> 
							</button>
							<button class="btn btn-sm">
								<span class="glyphicon glyphicon-heart-empty"></span> 
							</button>
						</div>	
						<div class="caption" style="border-top: 1px solid #DDDDDD; padding-top: 2px; margin-top: 10px; padding-bottom: 0px; margin-bottom: 0px; bckground: -moz-linear-gradient(top, rgba(54, 54, 54, .3), rgba(255, 255, 255, .1));"> 
							<p style="color: black" href="<?= $this->url('store/product', array('product_id' => $product['product_id']), array(), false); ?>"> 
								<?php
								if ($product->title == '') {
									echo $product->invoice_title;
								} else {
									echo $product->title;
								}
								?>
							</p>

							<!--
							<div style="max-height: 80px; text-overflow: ellipsis; overflow:hidden">
							<?php echo $product->description ?>
							</div>
							-->
							<!--
							<div><?php echo $product->characteristic ?></div>
							-->
							<div>
								<div style="float: right">								
									<span class="label label-info price"><?= $this->currencyFormat($product->price, "EUR", "fr_FR") . ' / ' . $product->unit_reference ?></span>
								</div>					
								<div class="input-group input-group" style="width: 120px; ">
									<input type="text" class="form-control" placeholder="Qty">
									<span class="input-group-addon">
										<button class=" btn btn-warning btn-xs" style="margin: 0">
											<span class="glyphicon glyphicon-shopping-cart"></span> 
											<?= $this->translate('Add') ?>
										</button>
									</span>
								</div>								
								<!--
																<a class="btn addto" href="#" rel="2">Add to <span class="glyphicon glyphicon-shopping-cart"></span></a> 
								-->								
							</div>
						</div>
					</div>
				</div>
				<?php if (((($idx + 1) % $columns) == 0) || $idx + 1 == $last_idx) : ?>				
				</div> <!-- end row -->	

			<?php endif; ?>
		<?php endforeach; ?>

		<!--</div>-->

		<div class="row">
			<div class="col-md-12">
				<?php
				echo $this->paginationControl($this->products->getPaginator(), 'Sliding', 'snippets/pagination_control', array('route' => 'test'));
				?>
			</div>	
		</div>

	</div>


</div>
<?php
$escaper = new Zend\Escaper\Escaper('utf-8');
$image_baseurl = "http://akilia2.emdmusic.com/medias/products/dynamic/";
?>
<script type="text/javascript">
					$('#product_search').typeahead([
						{
							name: 'dataset_brand_globalsearch',
							valueKey: 'reference',
							limit: 5,
							minLength: 1,
							header: '<h5 class="league-name"><?= $this->translate('Brands') ?></h5>',
							remote: {
								url: '<?=
$this->url('store/search', array(
	'action' => 'brand'
		//'categories' => $category['reference'],
		//'page' => 1
		), array(), $reuseMatchedParams = true)
?>?query=%QUERY',
								cache: true,
								timeout: 3000,
								filter: function(response) {
									//console.log('response', response);
									return response.data;
								}
							},
							template: [
								'<div>',
								'{{title}}',
								'</div>'
							].join(''),
							engine: Hogan

						},
						{
							name: 'dataset_product_globalsearch',
							valueKey: 'reference',
							limit: 30,
							minLength: 2,
							header: '<h5 class="league-name"><?= $this->translate('Products') ?></h5>',
							remote: {
								url: '<?=
$this->url('store/search', array(
	'action' => 'product'
		//'categories' => $category['reference'],
		//'page' => 1
		), array(), $reuseMatchedParams = true)
?>?query=%QUERY',
								cache: true,
								timeout: 3000,
								filter: function(response) {
									//console.log('response', response);
									return response.data;
								}
							},
							template: [
								'<div>',
								'<div style=";">',
								'<img src="<?= $image_baseurl ?>{{product_id}}-30x30_85.jpg" />',
								'<div style="float: right; style="width: 40px; height: 40px; overflow: hidden; border: 1px solid #E6E6E6; margin-right: 5px;>',
								'{{reference}}',
								'</div>',
								'</div>',
								'</div>'
							].join(''),
							engine: Hogan
						}]

							).on('typeahead:selected', function(e, data, data_set) {
						var new_location = '';
						if (data_set == 'dataset_brand_globalsearch') {
							var brand_reference = data.reference;
							new_location = '<?= $this->url('store/browse', array(), array(), false); ?>' + '/brands/' + brand_reference;
						} else if (data_set == 'dataset_product_globalsearch') {
							var product_id = data.product_id;
							new_location = '<?= $this->url('store/product', array('product_id' => ''), array(), false); ?>' + product_id;
						}
						if (new_location != '') {
							document.location.href = new_location;
						}
						return false;
					}
					);
</script>
