<div class="row">
	<div class="col-md-12">
		
		<?php $browse_filter = $this->searchParams->getFilter() ?>
		<ul class="nav nav-tabs">
			<li <?= ($browse_filter == '') ? 'class="active"' : '' ?>>
				<a href="<?= $this->url('store/browse', array('page' => 1, 'filter' => null)); ?>">All products</a>
			</li>
			<li <?= ($browse_filter == 'promos') ? 'class="active"' : '' ?>>
				<a href="<?= $this->url('store/browse', array('page' => 1, 'filter' => 'promos'), array(), $reuseMatchedParams = true); ?>">Promos</a>	
			</li>
			<li <?= ($browse_filter == 'new') ? 'class="active"' : '' ?>>
				<a href="<?= $this->url('store/browse', array('page' => 1, 'filter' => 'new'), array(), $reuseMatchedParams = true); ?>">New</a>
			</li>
			<li <?= ($browse_filter == 'onstock') ? 'class="active"' : '' ?>>
				<a href="<?= $this->url('store/browse', array('page' => 1, 'filter' => 'onstock'), array(), $reuseMatchedParams = true); ?>">On stock</a>
			</li>			
			<li <?= ($browse_filter == 'favourites') ? 'class="active pull-right"' : 'class="pull-right"' ?>>
				<a href="<?= $this->url('store/browse', array('page' => 1, 'filter' => 'favourites'), array(), $reuseMatchedParams = true); ?>"><span class="glyphicon glyphicon-heart"></span> Favorites</a> 
			</li>
		</ul>
	</div>
</div>
<br />
<div class="row">	
	<div class="col-md-3">
		<?php
		echo $this->partial('snippets/sidebar_navigation', array(
			'categories'	=> $this->categories,
			'brands'		=> $this->brands,
			'searchParams'	=> $this->searchParams
		))
		?>
	</div>


	<div class="col-md-9">

		<div class="row">	
			<?php
			$breadcrumb = $this->category_breadcrumb->toArray();
			$last_idx = count($breadcrumb) - 1;
			?>
			<?php if (count($breadcrumb) > 0) : ?>
			<div class="col-md-12">
				<ul class="breadcrumb">
					<?php foreach ($breadcrumb as $idx => $category) : ?>
						<?php if ($idx == $last_idx) : ?>
							<li class="active"><?= $category['title'] ?>
							<?php else: ?>
							<li><a href="<?=
								$this->url('store/browse', array(
									'categories' => $category['reference'],
									'page' => 1
										), array(), $reuseMatchedParams = true)
								?>"><?= $category['title'] ?></a></li>
						<?php endif; ?>
					<?php endforeach; ?>
					<?php
						$breadcrumb_brands = array();
						foreach ($this->brands as $brand) {
							if (in_array($brand['reference'], (array)  $this->searchParams->getBrands())) {
								$breadcrumb_brands[] = $brand['title'];
							} 
						}
					?>
					<?php if (count($breadcrumb_brands) > 0 && count($breadcrumb) > 0): ?>	
						<!-- <span class="pull-right"><a><?= '('  . join(', ', $breadcrumb_brands) . ')' ?></a></span> -->
					<?php endif; ?>
							
				</ul>
			</div>
			<?php endif; ?>	 
		</div>	
		
		
		<!--<div class="row">	-->

			<?php foreach ($this->products as $idx => $product) : ?>
			<?php 
				//echo "<h3>" . $idx % 3 . "</h3>";
				$columns = 3;
				$break = ($idx % $columns) == 0;	
				$last_idx = count($this->products);
			?>
			<?php if ($break) : ?>
<div class="row"> <!-- start row <?php echo "idx" . $idx . " --- ($idx % 3)" ?> -->	
			<?php endif; ?>	
				<div class="col-md-4">
					<!-- <div class="thumbnail wrapper"> -->
					<div class="thumbnail wrapper">
						<div class="ribbon-wrapper-green"><div class="ribbon-green"><?= $product->brand_title ?></div></div>
						<div>
							<div style="padding: 2px 2px;  background: rgba(54, 25, 25, .5); color: white; position: absolute">
								<span><?= $product->reference ?></span>
							</div>	 
							
							<div style="width: 100%; max-height: 200px; min-height: 80px; line-height: 150px; text-align: center;">
								 <a href="<?= $this->url('store/product', array('product_id' => $product['product_id']), array(), false); ?>">
									<img style="vertical-align: middle" src="http://akilia2.emdmusic.com/medias/products/dynamic/<?= $product->product_id ?>-170x200_90.jpg" alt="" />
								</a>
							</div>
						</div>
						
						<div class="caption" style="border-top: 1px solid black; margin-top: 1px"> 
							<a href="<?= $this->url('store/product', array('product_id' => $product['product_id']), array(), false); ?>"> 
								<?php echo $product->title ?>
							</a>
							<!--
							<div style="max-height: 80px; text-overflow: ellipsis; overflow:hidden">
								<?php echo $product->description ?>
							</div>
							-->
							<div><?php echo $product->characteristic ?></div>
							<p>
								<a class="btn primary details" href="#" rel="ajax/2.html"><span class="glyphicon glyphicon-zoom-in"></span></a> 
								<a class="btn addto" href="#" rel="2">Add to <span class="glyphicon glyphicon-shopping-cart"></span></a> 
								<span class="label label-info price"><?= $this->currencyFormat($product->price, "EUR", "fr_FR"); ?></span>
							</p>
						</div>
					</div>
				</div>
<?php if (((($idx+1) % $columns) == 0) || $idx+1 == $last_idx) : ?>				
</div><p></p> <!-- end row -->	

<?php endif; ?>
			<?php endforeach; ?>

		<!--</div>-->

		<div class="row">
			<div class="col-md-12">
				<?php
				echo $this->paginationControl($this->products->getPaginator(), 'Sliding', 'snippets/pagination_control', array('route' => 'test'));
				?>
			</div>	
		</div>

	</div>


</div>
