<div class="row">
	<div class="col-md-12">
		
		<?php $browse_filter = $this->searchParams->getFilter() ?>
		<ul class="nav nav-tabs">
			<li <?= ($browse_filter == '') ? 'class="active"' : '' ?>>
				<a href="<?= $this->url('store/browse', array('page' => 1, 'filter' => null)); ?>">All products</a>
			</li>
			<li <?= ($browse_filter == 'promos') ? 'class="active"' : '' ?>>
				<a href="<?= $this->url('store/browse', array('page' => 1, 'filter' => 'promos'), array(), $reuseMatchedParams = true); ?>">Promos</a>	
			</li>
			<li <?= ($browse_filter == 'new') ? 'class="active"' : '' ?>>
				<a href="<?= $this->url('store/browse', array('page' => 1, 'filter' => 'new'), array(), $reuseMatchedParams = true); ?>">New</a>
			</li>
			<li <?= ($browse_filter == 'onstock') ? 'class="active"' : '' ?>>
				<a href="<?= $this->url('store/browse', array('page' => 1, 'filter' => 'onstock'), array(), $reuseMatchedParams = true); ?>">On stock</a>
			</li>			
			<li <?= ($browse_filter == 'favourites') ? 'class="active pull-right"' : 'class="pull-right"' ?>>
				<a href="<?= $this->url('store/browse', array('page' => 1, 'filter' => 'favourites'), array(), $reuseMatchedParams = true); ?>"><span class="glyphicon glyphicon-heart"></span> Favorites</a> 
			</li>
		</ul>
	</div>
</div>
<br />
<div class="row">	
	<div class="col-md-3">
		<?php
		echo $this->partial('snippets/sidebar_navigation', array(
			'categories'	=> $this->categories,
			'brands'		=> $this->brands,
			'searchParams'	=> $this->searchParams
		))
		?>
	</div>


	<div class="col-md-9">

		<div class="row">	
			<div class="col-md-12">
				<ul class="breadcrumb">
					<?php
					$breadcrumb = $this->category_breadcrumb->toArray();
					$last_idx = count($breadcrumb) - 1;
					?>
					<?php foreach ($breadcrumb as $idx => $category) : ?>
						<?php if ($idx == $last_idx) : ?>
							<li class="active"><?= $category['title'] ?>
							<?php else: ?>
							<li><a href="#"><?= $category['title'] ?></a></li>
						<?php endif; ?>
					<?php endforeach; ?>
				</ul>
			</div>
		</div>	
		
		
		<div class="row">	

			<?php foreach ($this->products as $product) : ?>
				<div class="col-md-4">
					<div class="thumbnail wrapper">

						<div class="ribbon-wrapper-green"><div class="ribbon-green"><?= $product->brand_title ?></div></div>

						<div>
							<div class="span7">
								<a href="<?= $this->url('store/product', array('product_id' => $product['product_id']), array(), false); ?>"><img class="img-polaroid" src="http://akilia2.emdmusic.com/medias/products/dynamic/<?= $product->product_id ?>-150x120_90.jpg" alt=""></a>
							</div>
							<div class="span5">
								<h5  class="pull-left"><?= $product->reference ?></h5>
							</div>

						</div>
						<div class="caption"> <!-- style="background-repeat: no-repeat; background-image: url(http://akilia2.emdmusic.com/medias/products/dynamic/<?= $product->product_id ?>-150x120_90.jpg)"> -->
							<a href="<?= $this->url('store/product', array('product_id' => $product['product_id']), array(), false); ?>"> <h5><?php echo $product->title ?></h5></a><?= $product->reference ?>   
							<div style="max-height: 120px; text-overflow: ellipsis; overflow:hidden"><?php echo $product->description ?></div>
							<div><?php echo $product->characteristic ?></div>
							<p>
								<a class="btn primary details" href="#" rel="ajax/2.html"><span class="glyphicon glyphicon-zoom-in"></span></a> 
								<a class="btn addto" href="#" rel="2">Add to <span class="glyphicon glyphicon-shopping-cart"></span></a> 
								<span class="label label-info price"><?= $this->currencyFormat($product->price, "EUR", "fr_FR"); ?></span>
							</p>

						</div>
					</div>
				</div>
			<?php endforeach; ?>

		</div>		


		<?php
		echo $this->paginationControl($this->products->getPaginator(), 'Sliding', 'snippets/pagination_control', array('route' => 'test'));
		?>

	</div>


</div>
