<?php
	$escaper = new Zend\Escaper\Escaper('utf-8');
	$image_baseurl = "http://akilia2.emdmusic.com/medias/products/dynamic/";	
?>
<div class="row">
	<div class="col-md-12">
		<?php $browse_filter = $this->searchParams->getFilter()->getName(); ?>
		<ul class="nav nav-tabs">
			<li <?= ($browse_filter == '' || $browse_filter == 'all') ? 'class="active"' : '' ?>>
				<a href="<?= $this->url('store/browse', array('page' => 1, 'filter' => null)); ?>">All products</a>
			</li>
			<li <?= ($browse_filter == 'promos') ? 'class="active"' : '' ?>>
				<a href="<?= $this->url('store/browse', array('page' => 1, 'filter' => 'promos'), array(), $reuseMatchedParams = true); ?>">Promos</a>	
			</li>
			<li <?= ($browse_filter == 'new') ? 'class="active"' : '' ?>>
				<a href="<?= $this->url('store/browse', array('page' => 1, 'filter' => 'new'), array(), $reuseMatchedParams = true); ?>">New</a>
			</li>
			<li <?= ($browse_filter == 'onstock') ? 'class="active"' : '' ?>>
				<a href="<?= $this->url('store/browse', array('page' => 1, 'filter' => 'onstock'), array(), $reuseMatchedParams = true); ?>">On stock</a>
			</li>			
			<li <?= ($browse_filter == 'favourite') ? 'class="active pull-right"' : 'class="pull-right"' ?>>
				<a href="<?= $this->url('store/browse', array('page' => 1, 'filter' => 'favourites'), array(), $reuseMatchedParams = true); ?>"><span class="glyphicon glyphicon-heart"></span> Favorites</a> 
			</li>
		</ul>
	</div>
</div>
<br />
<div class="row">	
	<div class="col-md-3">
		<?php
		echo $this->partial('snippets/sidebar_navigation', array(
			'categories'	=> $this->categories,
			'brands'		=> $this->brands,
			'searchParams'	=> $this->searchParams
		))
		?>
	</div>
	<div class="col-md-9">
		<?php
		echo $this->partial('snippets/breadcrumb_control', array(
			'category_breadcrumb'	=> $this->category_breadcrumb,
			'searchParams'			=> $this->searchParams,
			'brands'				=> $this->brands
		))
		?>
		<div class="row">
				<div class="col-md-12" style="margin-bottom: 5px">
					<!-- <div class="thumbnail wrapper"> -->
					<div class="thumbnail wrapper">
						
						<div class="ribbon-wrapper-green">
							<div class="ribbon-green"><?= $product->brand_title ?></div>
						</div>
					<div>
					<?php if ($product->promo_discount > 0) : ?>	
					<div class="numbercircle">
						<strong>-<?= number_format($product->promo_discount) ?>%</strong><br />
					</div>
					<?php endif; ?>	
		
							<div style="padding: 2px 2px;  background: rgba(54, 25, 25, .5); color: white; position: absolute">
								<span><?= $product->reference ?></span>
							</div>	 
							
							<div style="width: 100%; max-height: 200px; min-height: 80px; line-height: 150px; text-align: center;">
								<a href="<?= $this->url('store/product', array('product_id' => $product['product_id']), array(), false); ?>">
									<img style="vertical-align: middle" src="<?= $image_baseurl . $product->product_id ?>-170x200_90.jpg" alt="" />
								</a>
							</div>
						</div>
						<div class="btn-group" style="float: right">
							<button class="btn btn-sm" onclick="javascript: $.colorbox({  maxWidth: '90%', maxHeight: '90%', title: '<?= $escaper->escapeJs((string) $product->brand_title) . ' &raquo; ' . $escaper->escapeJs((string) $product->reference) . ' &raquo; ' . $escaper->escapeJs((string) $product->title) ?>', href: '<?= $image_baseurl . $product->product_id ?>-1024x768_90.jpg?>'})">
								<span class="glyphicon glyphicon-zoom-in"></span> 
							</button>
							<button class="btn btn-sm">
								<span class="glyphicon glyphicon-info-sign"></span> 
							</button>
							<button class="btn btn-sm">
								<span class="glyphicon glyphicon-heart-empty"></span> 
							</button>
						</div>	
						<div class="caption" style="border-top: 1px solid #DDDDDD; padding-top: 2px; margin-top: 10px; padding-bottom: 0px; margin-bottom: 0px; bckground: -moz-linear-gradient(top, rgba(54, 54, 54, .3), rgba(255, 255, 255, .1));"> 
							<p style="color: black" href="<?= $this->url('store/product', array('product_id' => $product['product_id']), array(), false); ?>"> 
								<?php 
									if ($product->title == '') {
										echo $product->invoice_title;
									} else {
										echo $product->title;
									}
								?>
							</p>
							<div style="max-height: 80px; text-overflow: ellipsis; overflow:hidden">
								<?php echo $product->description ?>
							</div>
							<div><?php echo $product->characteristic ?></div>
							<div>
								<div style="float: right">								
									<span class="label label-info price"><?= $this->currencyFormat($product->price, "EUR", "fr_FR") . ' / ' . 'PC'?></span>

								</div>					
								<div class="input-group input-group" style="width: 120px; ">
									
								  <input type="text" class="form-control" placeholder="Qty">
								  <span class="input-group-addon">
		  
								  <button class=" btn btn-warning btn-xs" style="margin: 0">
									  <span class="glyphicon glyphicon-shopping-cart"></span> 
									  Add
								  </button>
								  </span>
								</div>								
<!--
								<a class="btn addto" href="#" rel="2">Add to <span class="glyphicon glyphicon-shopping-cart"></span></a> 
-->								
							</div>
						</div>
					</div>
				</div>
	</div> <!-- end row -->	



	</div>


</div>