<!--
<div class="row">
	<div class="span12">
		<ul class="nav nav-tabs">
			<li class="active">
				<a href="#">All products</a>
			</li>
			<li>
				<a href="#">Promos</a>	
			</li>
			<li>
				<a href="#">New</a>
			</li>
			<li>
				<a href="#">On stock</a>
			</li>			
			
			<li class="pull-right">
				<a href="#"><i class="icon-heart"></i> Favorites</a> 
			</li>
		
		</ul>
	</div>
</div>	
-->
<div class="row">
	
	
	
	<div class="span3">
		<?php echo $this->partial('snippets/categories_hmenu', 
				array(
					'categories' => $this->categories,
					'brands'	 => $this->brands, 
		)) ?>
	</div>

	<!--
	<div class="span9">
		<?php echo $this->partial('snippets/main_carousel', array()); ?>
	</div>
	-->
	<div class="span9">
		<ul class="breadcrumb">
			<?php
				$breadcrumb = $this->category_breadcrumb->toArray();
				$last_idx = count($breadcrumb) - 1;
			?>
			<?php foreach($breadcrumb as $idx => $category) : ?>
				<?php if ($idx == $last_idx ) : ?>
					<li class="active"><?= $category['title'] ?>
					
				<?php else: ?>
					<li><a href="#"><?= $category['title'] ?></a> <span class="divider">/</span></li>
				<?php endif; ?>
				
			<?php endforeach; ?>
			
		</ul>	
	</div>

	<div class="span9">
		<ul class="nav nav-tabs">
			<li class="active">
				<a href="#">All products</a>
			</li>
			<li>
				<a href="#">Promos</a>	
			</li>
			<li>
				<a href="#">New</a>
			</li>
			<li>
				<a href="#">On stock</a>
			</li>			
			
			<li class="pull-right">
				<a href="#"><i class="icon-heart"></i> Favorites</a> 
			</li>
		
		</ul>
	</div>
	<style>
.ribbon-banner {
   display: block;
   position: relative;
   top: 50px;
   left: -120px;
   width: 400px;
   height: 50px;
   line-height: 50px;
   text-align: center;
   opacity: 0.7;
   -webkit-transform: rotate(-45deg);
   -moz-transform:    rotate(-45deg);
   -ms-transform:     rotate(-45deg);
   transform:         rotate(-45deg);
   font-size: 24px;
   font-weight: 700;
   color: white;
   background-color: red;
   border: 1px solid white;
   z-index: 500;
   }
/* other */

.wrapper {
  border-radius: 10px;
  -webkit-box-shadow: 0px 0px 8px rgba(0,0,0,0.3);
  -moz-box-shadow:    0px 0px 8px rgba(0,0,0,0.3);
  box-shadow:         0px 0px 8px rgba(0,0,0,0.3);
  position: relative;
  z-index: 90;
}

.ribbon-wrapper-green {
  width: 85px;
  height: 80px;
  overflow: hidden;
  position: absolute;
  top: -3px;
  right: -3px;
}

.ribbon-green {
  /*font: bold 15px Sans-Serif;*/
  color: #333;
  text-align: center;
  text-shadow: rgba(255,255,255,0.5) 0px 1px 0px;
  -webkit-transform: rotate(45deg);
  -moz-transform:    rotate(45deg);
  -ms-transform:     rotate(45deg);
  -o-transform:      rotate(45deg);
  position: relative;
  padding: 7px 0;
  left: -5px;
  top: 15px;
  width: 120px;
  background-color: #BFDC7A;
  background-image: -webkit-gradient(linear, left top, left bottom, from(#BFDC7A), to(#8EBF45)); 
  background-image: -webkit-linear-gradient(top, #BFDC7A, #8EBF45); 
  background-image:    -moz-linear-gradient(top, #BFDC7A, #8EBF45); 
  background-image:     -ms-linear-gradient(top, #BFDC7A, #8EBF45); 
  background-image:      -o-linear-gradient(top, #BFDC7A, #8EBF45); 
  color: #6a6340;
  -webkit-box-shadow: 0px 0px 3px rgba(0,0,0,0.3);
  -moz-box-shadow:    0px 0px 3px rgba(0,0,0,0.3);
  box-shadow:         0px 0px 3px rgba(0,0,0,0.3);
}
/*
.ribbon-green:before, .ribbon-green:after {
  content: "";
  border-top:   3px solid #6e8900;   
  border-left:  3px solid transparent;
  border-right: 3px solid transparent;
  position:absolute;
  bottom: -3px;
}

.ribbon-green:before {
  left: 0;
}
.ribbon-green:after {
  right: 0;
}
*/
	</style>	
	
	<div class="span9">
		<!-- <h4>Articles populaires</h4><br> -->
		<div class="thumbnails">
			<?php foreach($this->products as $product) :  ?>
			<li class="span3">
				<div class="thumbnail wrapper">

					<div class="ribbon-wrapper-green"><div class="ribbon-green"><?= $product->brand_title ?></div></div>
					
					<div class="row-fluid">
						<div class="span7">
							<a href="<?= $this->url('store/product', array('product_id' => $product['product_id']), array(), false); ?>"><img class="img-polaroid" src="http://akilia2.emdmusic.com/medias/products/dynamic/<?= $product->product_id ?>-150x120_90.jpg" alt=""></a>
						</div>
						<div class="span5">
							<h5  class="pull-left"><?= $product->reference ?></h5>
							
						</div>
						
					</div>
					<div class="caption"> <!-- style="background-repeat: no-repeat; background-image: url(http://akilia2.emdmusic.com/medias/products/dynamic/<?= $product->product_id ?>-150x120_90.jpg)"> -->
						<a href="product.html"> <h5><?php echo $product->title ?></h5></a><?= $product->reference ?>   
						<div style="max-height: 120px; text-overflow: ellipsis; overflow:hidden"><?php echo $product->description ?></div>
						<div><?php echo $product->characteristic ?></div>
						<p><a class="btn primary details" href="#" rel="ajax/2.html"><i class="icon-zoom-in"></i></a> <a class="btn addto" href="#" rel="2">Add to <i class="icon-shopping-cart"></i></a> <span class="label label-info price"><?= $this->currencyFormat($product->price, "EUR", "fr_FR"); ?></span></p>
						
					</div>
				</div>
			</li>
			<?php endforeach; ?>
		</div>
		<div class="pagination pagination-centered pagination-large">
			<ul>
			<li><a href="#">Prev</a></li>
			<li><a href="#">1</a></li>
			<li><a href="#">2</a></li>
			<li><a href="#">3</a></li>
			<li><a href="#">4</a></li>
			<li><a href="#">5</a></li>
			<li><a href="#">Next</a></li>
			</ul>
	    </div>
</div>
	
	
</div>
