<?php
$esc = new Zend\Escaper\Escaper('utf-8');
$picture_url_spec = "http://api.emdmusic.com/media/picture/%picture_media_id%_1024x768-90.jpg";
?>
<?= '<?xml version="1.0" encoding="utf-8" ?>' . "\n"; ?>
<NAMM_ITEM xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://namm.org/b2b/2009/schemas" version="2011.1">

  <!--
  <Timestamp>2011-08-11T05:39:10.887</Timestamp>
  <Id>38A6C25A-2344-4343-B53D-B8706E1A37DA</Id>
  <SupplierId>0670716045609</SupplierId>
  -->
  <Items>
    <?php foreach($this->data as $line) : ?>
    <Item>
      <SupplierItemId><?= $line->product_id ?></SupplierItemId>
      <SupplierModel><?= $esc->escapeHtml($line->product_reference) ?></SupplierModel>
      <SupplierItemDesc><?= $esc->escapeHtml($line->product_reference . ', ' . $line->product_title) ?></SupplierItemDesc>
      <ItemDesc><?= $esc->escapeHtml($line->product_title) ?></ItemDesc>
      <ItemDescLong><?=  $esc->escapeHtml(trim($line->product_title . ' ' . $line->product_description . ' ' . $line->product_characteristic)) ?></ItemDescLong>      
      <BrandName><?= $esc->escapeHtml($line->brand_title) ?></BrandName>
      <Category><?= $esc->escapeHtml($line->category_title) ?></Category>
      <Images>
          <ImageURL><?= str_replace('%picture_media_id%', $line->picture_media_id, $picture_url_spec); ?></ImageURL>
      </Images>      
      <!--
      <CountryOrigin>IT</CountryOrigin>
      <Length>30.0000</Length>
      <Width>20.0000</Width>
      <Height>15.0000</Height>
      <DimUOM>IN</DimUOM>
      -->
      <Weight><?= $line['weight'] ?></Weight>
      <WeightUOM>KG</WeightUOM>
      <!--
      <AnnounceDate>2008-01-17</AnnounceDate>
      <AvailableDate>2008-02-17</AvailableDate>
      <UnavailableDate>2012-01-05</UnavailableDate>
      -->
      <WarrantyPartTerm>365</WarrantyPartTerm>
      <WarrantyPartUOM>Day</WarrantyPartUOM>
      <WarrantyLabTerm>0</WarrantyLabTerm>
      <WarrantyLabUOM>Day</WarrantyLabUOM>
      <Barcodes>
        <Barcode>
          <ID><?= $line->product_barcode_upca ?></ID>
          <Type>GTIN-12</Type>
        </Barcode>
        <Barcode>
          <ID><?= $line->product_barcode_ean13 ?></ID>
          <Type>GTIN-13</Type>
        </Barcode>
      </Barcodes>
      <Pricing>
        <Price type="MSRP"
               Currency="<?= $line->currency_reference ?>"><?= $line->public_price ?></Price>
        <Price type="MAP"
               Currency="<?= $line->currency_reference ?>"><?= $line->price ?></Price>
      </Pricing>
      <Containers>
        <Container>
          <Type>Each</Type>
          <Length><?=  $line->pack_unit_length ?></Length>
          <Width><?=  $line->pack_unit_width ?></Width>
          <Height><?=  $line->pack_unit_height ?></Height>11
          <DimUOM>M</DimUOM>
          <Weight><?=  $line->pack_unit_weight * 2.20462 ?></Weight>
          <WeightUOM>LBS</WeightUOM>
          <UOM>EA</UOM>
          <QtyPerUOM>1</QtyPerUOM>
          <Barcodes>
            <Barcode>
              <ID><?=  $line->product_barcode_ean13 ?></ID>
              <Type>GTIN-13</Type>
            </Barcode>
            <Barcode>
              <ID><?=  $line->product_barcode_upca ?></ID>
              <Type>GTIN-12</Type>
            </Barcode>
          </Barcodes>          
        </Container>
        <Container>
          <Type>Box</Type>
          <Length><?=  $line->pack_box_length ?></Length>
          <Width><?=  $line->pack_box_width ?></Width>
          <Height><?=  $line->pack_box_height ?></Height>
          <DimUOM>M</DimUOM>
          <Weight><?=  $line->pack_box_weight * 2.20462 ?></Weight>
          <WeightUOM>LBS</WeightUOM>
          <UOM>BX</UOM>
          <QtyPerUOM><?= $line->pack_qty_box ?></QtyPerUOM>
          <Barcodes>
            <Barcode>
              <ID><?=  $line->pack_box_barcode_ean ?></ID>
              <Type>GTIN-14</Type>
            </Barcode>
            <Barcode>
              <ID><?=  $line->pack_box_barcode_upc ?></ID>
              <Type>GTIN-13</Type>
            </Barcode>
          </Barcodes>          
        </Container>          
        <Container>
          <Type>Carton</Type>
          <Length><?=  $line->pack_mastercarton_length ?></Length>
          <Width><?=  $line->pack_mastercarton_width ?></Width>
          <Height><?=  $line->pack_mastercarton_height ?></Height>
          <DimUOM>M</DimUOM>
          <Weight><?=  $line->pack_mastercarton_weight ?></Weight>
          <WeightUOM>KG</WeightUOM>
          <UOM>CTN</UOM>
          <QtyPerUOM><?= $line->pack_qty_master_carton ?></QtyPerUOM>
          <Barcodes>
            <Barcode>
              <ID><?=  $line->pack_mastercarton_barcode_ean ?></ID>
              <Type>GTIN-14</Type>
            </Barcode>
            <Barcode>
              <ID><?=  $line->pack_mastercarton_barcode_upc ?></ID>
              <Type>GTIN-13</Type>
            </Barcode>
          </Barcodes>          
        </Container>          
          
      </Containers>
    </Item>
    <?php endforeach; ?>  
  </Items>
</NAMM_ITEM>