<?php
use PhpUnitsOfMeasure\PhysicalQuantity\Mass;
use PhpUnitsOfMeasure\PhysicalQuantity\Length;

function convertKgmInLbs($kg) {
    if ($kg == "")  return '';
    $mass = new Mass($kg, 'kg');
    $lbs = number_format($mass->toUnit('lbs'), 2);
    return $lbs;
}

function convertMeterInInch($meter) {
    if ($meter == "")  return '';
    $length = new Length($meter, 'meter');
    $inches = number_format($length->toUnit('inch'), 2);
    return $inches;
}

$esc = new Zend\Escaper\Escaper('utf-8');

$picture_url_spec = "http://api.emdmusic.com/media/picture/%picture_media_id%_1024x768-90.jpg";
?>
<?= '<?xml version="1.0" encoding="utf-8" ?>' . "\n"; ?>
<NAMM_ITEM version="2007.1">
  <SupplierId></SupplierId>    
  <Items>
    <?php foreach($this->data as $line) : ?>
    <Item>
        <SupplierItemId><?= $line->product_id ?></SupplierItemId>
        <SupplierModel><?= $esc->escapeHtml(trim($line->product_reference)) ?></SupplierModel>
        <ItemDesc><?= $esc->escapeHtml(trim($line->product_title)) ?></ItemDesc>
        <ItemDescLong><![CDATA[<?php
                $desc = trim($line->product_title . ' ' . $line->product_description . ' ' . $line->product_characteristic);
                echo preg_replace('/(\ ){2,}/', ' ', $desc); ?>]]>
        </ItemDescLong>      
        
        <!--
            MSRP price
        -->
        <RetailValue><?= number_format($line->public_price, 2); ?></RetailValue>
        
        <!--
            Unit cost value, price for the dealer
        -->
        <UCValue><?= number_format($line->price, 2); ?></UCValue>
        
        <!--
            Mainly China
        -->
        <CountryOrigin></CountryOrigin>
        
        <BrandName><?= $esc->escapeHtml($line->brand_name) ?></BrandName>
        <!--
            Package dimensions may  not yet known on product level,
            and include packaging (product in its box).
            Item description will inform about exact dimensions.
        -->
        <Length><?= convertMeterInInch($line->pack_unit_length) ?></Length>
        <Width><?= convertMeterInInch($line->pack_unit_width) ?></Width>
        <Height><?= convertMeterInInch($line->pack_unit_height) ?></Height>
        <DimUOM>In</DimUOM>
        
        <Weight><?= convertKgmInLbs($line->weight); ?></Weight>
        <WeightUOM>Lbs</WeightUOM>
        
        <!--
           Barcode in UPCA as printed for US and Canada markets
        -->
        <BarCodeId><?= $line->product_barcode_upca ?></BarCodeId>
        <BarCodeDesc>UPC</BarCodeDesc>
        
        <!--
            Carton dimensions may not be known.
            Master carton dimensions should always be known.
        -->
        <CLength><?= convertMeterInInch($line->pack_carton_length) ?></CLength>
        <CWidth><?= convertMeterInInch($line->pack_carton_width) ?></CWidth>
        <CHeight><?= convertMeterInInch($line->pack_carton_height) ?></CHeight>
        <CWeight><?= convertKgmInLbs($line->pack_carton_weight) ?></CWeight>
        <CDimUOM>In</CDimUOM>
        <CWeightUOM>Lbs</CWeightUOM>
        

        <CUOM>EA</CUOM> <!-- EACH, see code table -->
        <CQtyPerUOM><?php 
            $pack_qty_carton = $line->pack_qty_carton;
            if ($pack_qty_carton != '') {
                echo number_format($pack_qty_carton, 0);
            }
      ?></CQtyPerUOM>
        
        <!-- 
            Internal carton does not apply
        -->
        <ICBarcodeId></ICBarcodeId>
        <ICBarcodeDesc></ICBarcodeDesc>
        <ICLength></ICLength>
        <ICWidth></ICWidth>
        <ICHeight></ICHeight>
        <ICWeight></ICWeight>
        <ICDimUOM></ICDimUOM>
        <ICWeightUOM></ICWeightUOM>
        <ICUOM></ICUOM>
        <ICQtyPerUOM></ICQtyPerUOM>
        <!--
            Master carton information
        -->
        <MCBarcodeId><?= $line->pack_mastercarton_barcode_upc ?></MCBarcodeId>
        <MCBarCodeType>UPC</MCBarCodeType>
        <MCBarcodeDesc></MCBarcodeDesc>
        <MCLength><?= convertMeterInInch($line->pack_mastercarton_length) ?></MCLength>
        <MCWidth><?= convertMeterInInch($line->pack_mastercarton_width) ?></MCWidth>
        <MCHeight><?= convertMeterInInch($line->pack_mastercarton_height) ?></MCHeight>
        <MCWeight><?= convertKgmInLbs($line->pack_mastercarton_weight) ?></MCWeight>
        <MCDimUOM>In</MCDimUOM>
        <MCWeightUOM>Lbs</MCWeightUOM>
        <MCUOM>EA</MCUOM> <!-- EACH -->
        <MCQtyPerUOM><?php 
            $pack_qty_master_carton = $line->pack_qty_master_carton;
            if ($pack_qty_master_carton != '') {
                echo number_format($pack_qty_master_carton, 0);
            }
      ?></MCQtyPerUOM>
        <Kit>false</Kit>
        <!--
            If the product has a serial number
        -->
        <Serialized>true</Serialized>
        <!--
            Color and size are not yet known.
            Refer to item description
        -->
        <Color></Color>
        <Size></Size>
        
        <!-- Announce date is not known on our system -->
        <AnnounceDate></AnnounceDate>
        
        
        <!--
            TODO: available date quality may be poor
        -->
        <AvailableDate><?= $line->available_at ?></AvailableDate>
        <!--
            Unavailable date is not known in our system
        -->
        <UnAvailDate></UnAvailDate>
        <EndOfProductionDate></EndOfProductionDate>
        <Replacement></Replacement>
        
        <!--
            TODO: Warranty conditions still to be determined
        --> 
        <WarrantyPartTerm>90</WarrantyPartTerm>
        <WarrantyPartUOM>Day</WarrantyPartUOM>
        <WarrantyLabTerm>365</WarrantyLabTerm>
        <WarrantyLabUOM>Day</WarrantyLabUOM>
        <Category><?= $esc->escapeHtml(str_replace("|", "/", $line->category_breadcrumb)) ?></Category>
        
        <Images>
            <?php if ($line->picture_media_id != '') : ?>
            <ImageURL><?= str_replace('%picture_media_id%', $line->picture_media_id, $picture_url_spec); ?></ImageURL>
            <?php else : ?>
                <?= "<!-- No picture yet -->" ?>
            <?php endif; ?>
        </Images>
        <!--
            Product information url not yet available, see on staggmusic.com website.
        -->
        <ProductURL></ProductURL>
    </Item>
    <?php endforeach; ?>  
  </Items>
</NAMM_ITEM>