<?php
$esc = new Zend\Escaper\Escaper('utf-8');
$picture_url_spec = "http://api.emdmusic.com/media/picture/%picture_media_id%_1024x768-90.jpg";
?>
<?= '<?xml version="1.0" encoding="utf-8" ?>' . "\n"; ?>
<NAMM_ITEM xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://namm.org/b2b/2009/schemas" version="2011.1">

  <!--
  <Timestamp>2011-08-11T05:39:10.887</Timestamp>
  <Id>38A6C25A-2344-4343-B53D-B8706E1A37DA</Id>
  <SupplierId>0670716045609</SupplierId>
  -->
  <Items>
    <?php foreach($this->data as $line) : ?>
    <Item>
      <SupplierItemId><?= $line->product_id ?></SupplierItemId>
      <SupplierModel><?= $esc->escapeHtmlAttr($line->product_reference) ?></SupplierModel>
      <SupplierItemDesc><?= $esc->escapeHtmlAttr($line->product_reference . ', ' . $line->product_title) ?></SupplierItemDesc>
      <ItemDesc><?= $esc->escapeHtmlAttr($line->product_title) ?></ItemDesc>
      <ItemDescLong><?=  $esc->escapeHtmlAttr(trim($line->product_title . ' ' . $line->product_description . ' ' . $line->product_characteristic)) ?></ItemDescLong>      
      <BrandName><?= $esc->escapeHtmlAttr($line->brand_title) ?></BrandName>
      <Category><?= $esc->escapeHtmlAttr($line->category_title) ?></Category>
      <Images>
          <ImageURL><?= str_replace('%picture_media_id%', $line->picture_media_id, $picture_url_spec); ?></ImageURL>
      </Images>      
      <!--
      <CountryOrigin>IT</CountryOrigin>
      <Length>30.0000</Length>
      <Width>20.0000</Width>
      <Height>15.0000</Height>
      <DimUOM>IN</DimUOM>
      -->
      <Weight><?= $line['weight'] ?></Weight>
      <WeightUOM>KG</WeightUOM>
      <!--
      <AnnounceDate>2008-01-17</AnnounceDate>
      <AvailableDate>2008-02-17</AvailableDate>
      <UnavailableDate>2012-01-05</UnavailableDate>
      -->
      <WarrantyPartTerm>365</WarrantyPartTerm>
      <WarrantyPartUOM>Day</WarrantyPartUOM>
      <WarrantyLabTerm>0</WarrantyLabTerm>
      <WarrantyLabUOM>Day</WarrantyLabUOM>
      <Barcodes>
        <Barcode>
          <ID><?= $line->product_barcode_upca ?></ID>
          <Type>GTIN-12</Type>
        </Barcode>
        <Barcode>
          <ID><?= $line->product_barcode_ean13 ?></ID>
          <Type>GTIN-13</Type>
        </Barcode>
      </Barcodes>
      <Pricing>
        <Price type="MSRP"
               Currency="<?= $line->currency_reference ?>"><?= $line->public_price ?></Price>
        <Price type="MAP"
               Currency="<?= $line->currency_reference ?>"><?= $line->price ?></Price>
      </Pricing>
      <Containers>
        <Container>
          <Type>Each</Type>
          <Length><?=  $line->pack_unit_length ?></Length>
          <Width><?=  $line->pack_unit_width ?></Width>
          <Height><?=  $line->pack_unit_height ?></Height>11
          <DimUOM>M</DimUOM>
          <Weight><?=  $line->pack_unit_weight * 2.20462 ?></Weight>
          <WeightUOM>LBS</WeightUOM>
          <UOM>EA</UOM>
          <QtyPerUOM>1</QtyPerUOM>
          <Barcodes>
            <Barcode>
              <ID><?=  $line->product_barcode_ean13 ?></ID>
              <Type>GTIN-13</Type>
            </Barcode>
            <Barcode>
              <ID><?=  $line->product_barcode_upca ?></ID>
              <Type>GTIN-12</Type>
            </Barcode>
          </Barcodes>          
        </Container>
        <Container>
          <Type>Box</Type>
          <Length><?=  $line->pack_box_length ?></Length>
          <Width><?=  $line->pack_box_width ?></Width>
          <Height><?=  $line->pack_box_height ?></Height>
          <DimUOM>M</DimUOM>
          <Weight><?=  $line->pack_box_weight * 2.20462 ?></Weight>
          <WeightUOM>LBS</WeightUOM>
          <UOM>BX</UOM>
          <QtyPerUOM><?= $line->pack_qty_box ?></QtyPerUOM>
          <Barcodes>
            <Barcode>
              <ID><?=  $line->pack_box_barcode_ean ?></ID>
              <Type>GTIN-14</Type>
            </Barcode>
            <Barcode>
              <ID><?=  $line->pack_box_barcode_upc ?></ID>
              <Type>GTIN-13</Type>
            </Barcode>
          </Barcodes>          
        </Container>          
        <Container>
          <Type>Carton</Type>
          <Length><?=  $line->pack_mastercarton_length ?></Length>
          <Width><?=  $line->pack_mastercarton_width ?></Width>
          <Height><?=  $line->pack_mastercarton_height ?></Height>
          <DimUOM>M</DimUOM>
          <Weight><?=  $line->pack_mastercarton_weight ?></Weight>
          <WeightUOM>KG</WeightUOM>
          <UOM>CTN</UOM>
          <QtyPerUOM><?= $line->pack_qty_master_carton ?></QtyPerUOM>
          <Barcodes>
            <Barcode>
              <ID><?=  $line->pack_mastercarton_barcode_ean ?></ID>
              <Type>GTIN-14</Type>
            </Barcode>
            <Barcode>
              <ID><?=  $line->pack_mastercarton_barcode_upc ?></ID>
              <Type>GTIN-13</Type>
            </Barcode>
          </Barcodes>          
        </Container>          
          
      </Containers>
    </Item>
    <?php endforeach; ?>  
      <!--Musical Instrument Guitar Example-->
      <!--
    <Item>
      <SupplierItemId>G100ACE</SupplierItemId>
      <SupplierModel>G100ACE</SupplierModel>
      <SupplierItemDesc>G100 Stage Series Auditorium Cutaway
      Electric</SupplierItemDesc>
      <Kit>N</Kit>
      <Serialized>Y</Serialized>
      <BrandName>LAG</BrandName>
      <Length>50.0000</Length>
      <Width>20.0000</Width>
      <Height>10.0000</Height>
      <DimUOM>IN</DimUOM>
      <Weight>10</Weight>
      <WeightUOM>LBS</WeightUOM>
      <AnnounceDate>2010-01-15</AnnounceDate>
      <AvailableDate>2010-02-15</AvailableDate>
      <WarrantyPartTerm>365</WarrantyPartTerm>
      <WarrantyPartUOM>Day</WarrantyPartUOM>
      <WarrantyLabTerm>0</WarrantyLabTerm>
      <WarrantyLabUOM>Day</WarrantyLabUOM>
      <Barcodes>
        <Barcode>
          <ID>3700166330283</ID>
          <Type>GTIN-13</Type>
        </Barcode>
      </Barcodes>
      <Pricing>
        <Price type="MSRP"
               Currency="USD">675.00</Price>
        <Price type="MAP"
               Currency="USD">4</Price>
        <Price type="Cost"
               Currency="USD"
               Qty="1">3</Price>
      </Pricing>
      <Containers>
        <Container>
          <Type>Each</Type>
          <Length>41.3300</Length>
          <Width>18.5000</Width>
          <Height>5.1100</Height>
          <DimUOM>IN</DimUOM>
          <Weight>6.3900</Weight>
          <WeightUOM>LBS</WeightUOM>
          <UOM>EA</UOM>
          <QtyPerUOM>1</QtyPerUOM>
          <Barcodes>
            <Barcode>
              <ID>3700166330283</ID>
              <Type>GTIN-13</Type>
            </Barcode>
          </Barcodes>
        </Container>
        <Container>
          <Type>Case Pack</Type>
          <Length>42.3200</Length>
          <Width>42.3200</Width>
          <Height>5.7000</Height>
          <DimUOM>IN</DimUOM>
          <Weight>12.780000000000</Weight>
          <WeightUOM>LBS</WeightUOM>
          <UOM>CS</UOM>
          <QtyPerUOM>2</QtyPerUOM>
        </Container>
      </Containers>
      <MarketingInfo>
        <PrimaryCategory>4025131110</PrimaryCategory>
        <ProductURL>
        http://gorkguitars.com/?page=fp&amp;np=14&amp;sg=1</ProductURL>
        <ItemDescLong>The Stage Range starts with the high-gloss
        G100 Series. Maple, mahogany, and black binding join the
        dark mahogany back and sides to the solid Red Cedar top and
        add character to the Occitan Cross rosette. The
        honey-mahogany neck features a comfortable French satin
        finish and a smooth Indonesian rosewood
        fingerboard.</ItemDescLong>
        <Bullets>
          <Bullet>High-gloss natural finish; Red Cedar top with
          dark mahogany back and sides</Bullet>
          <Bullet>Maple, mahogany, and black colored body binding
          &amp; Occitan Cross rosette pattern</Bullet>
          <Bullet>French satin-finished honey mahogany neck;
          Indonesian rosewood fingerboard</Bullet>
          <Bullet>StudioLuge electronic system; five
          expertly voiced EQ settings, volume control</Bullet>
          <Bullet>Flexible NanoFlex piezo pickup mounted in the
          bridge, under the saddle</Bullet>
        </Bullets>
      </MarketingInfo>
      <RelatedItems>
        <RelatedItem included="Y"
                     type="accessory">
          <SupplierItemId>D8B5518003B</SupplierItemId>
          <Barcode>
            <ID>1234567890123</ID>
            <Type>GTIN-13</Type>
          </Barcode>
        </RelatedItem>
        <RelatedItem included="N"
                     type="ThirdParty">
          <SupplierItemId>ProductX</SupplierItemId>
          <Barcode>
            <ID>1112345678911</ID>
            <Type>GTIN-13</Type>
          </Barcode>
        </RelatedItem>
      </RelatedItems>
    </Item>
-->
  </Items>
</NAMM_ITEM>