<h1>qsdqsdkjlSign In</h1>

<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
?>


<form role="form" action="<?= $form->getAttribute('action') ?>" method="<?= $form->getAttribute('method') ?>">
  <div class="form-group">
    <label for="authInputEmail1"><?= $this->translate('Email address') ?></label>
    <input type="text" name="identity" class="form-control" id="authInputEmail1" placeholder="Enter email">
  </div>
  <div class="form-group">
    <label for="authInputPassword1">Password</label>
    <input type="password" name="credential" class="form-control" id="authInputPassword1" placeholder="Password">
  </div>
	<?php if ($this->redirect): ?>
		<input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
	<?php endif ?>
  <div class="checkbox">
    <label>
      <input type="checkbox"> <?= $this->translate('Remember me') ?>
    </label>
  </div>
  <button type="submit" class="btn btn-default"><?= $this->translate('Sign in') ?></button>
</form>
<?php echo $this->formElementErrors($form->get('identity')) ?>

<?php if ($this->enableRegistration) : ?>
Not registered? <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>">Sign up!</a>
<?php endif; ?>
