<?php
namespace Openstore\Model;

use Openstore\Model\Category;
use ModulesTests\ServiceManagerGrabber;
use Zend\ServiceManager\ServiceManager;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-10-13 at 19:23:29.
 */
class CategoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Category
     */
    protected $category;

    /**
     *
     * @var ServiceManager
     */
    protected $serviceManager;
    
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $serviceManagerGrabber   = new ServiceManagerGrabber();
        $this->serviceManager = $serviceManagerGrabber->getServiceManager();
        
        $this->category = $this->serviceManager->get('Model\Category');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }


    public function testGetBrowser()
    {
        $browser = $this->category->getBrowser();
        $this->assertInstanceOf('Openstore\Model\Browser\CategoryBrowser', $browser);
        $this->assertInstanceOf('Openstore\Core\Model\Browser\AbstractBrowser', $browser);
    }
}
