<?php echo $this->doctype(); ?>
<html lang="en">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<meta charset="utf-8">
		<?php echo $this->headTitle('Openstore ' . $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>
		<?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
		<meta name="description" content="">
		<meta name="author" content="">
		<?php
		$theme_path = $this->basePath() . '/themes/openstore'
		?>
		<?php
		echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
				->prependStylesheet($theme_path . '/css/main.css')
				->prependStylesheet($theme_path . '/resources/bootstrap-themes/united/bootstrap.min.css')
				//->prependStylesheet('//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css')
				->prependStylesheet($theme_path . '/resources/jquery-colorbox/example3/colorbox.css')
				//->prependStylesheet('//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.min.css')
				//->prependStylesheet($theme_path . '/resources/bootstrap-glyphicons/css/bootstrap-glyphicons.css')
				->prependStylesheet($theme_path . '/resources/bootstrap/css/bootstrap.min.css')
				//->prependStylesheet($theme_path . '/resources/twitter-typeahead/css/typeahead.js-bootstrap.css')
				->prependStylesheet($theme_path . '/resources/jquery-select2/select2.css')
				->prependStylesheet($theme_path . '/resources/jquery-select2-bootstrap/select2-bootstrap.css')
		?>

		<?php
		echo $this->headScript()
				->prependFile($theme_path . '/js/main.js')
				->prependFile($theme_path . '/resources/jquery-select2/select2.js')
				->prependFile($theme_path . '/resources/twitter-typeahead/js/typeahead.min.js')
				->prependFile($theme_path . '/resources/twitter-hogan/hogan-2.0.0.js')
				->prependFile($theme_path . '/resources/bootstrap/js/bootstrap.min.js')
				->prependFile($theme_path . '/resources/jquery-colorbox/jquery.colorbox-min.js')
				->prependFile($theme_path . '/resources/jquery-color/jquery.color.js')
				->prependFile($theme_path . '/resources/jquery/jquery.min.js')
		?>

		<!-- Make IE8 and below responsive by adding CSS3 MediaQuery support and html5-->
		<!--[if lt IE 9]>
			<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
			<script type="text/javascript" src="http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js"></script>
		<![endif]-->

	</head>

	<body>
        <!--[if lt IE 7]>
            <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
        <![endif]-->
		
		
		<?php
		echo $this->partial('snippets/main_navbar', array(
			//'categories'	=> $this->categories,
			//'brands'		=> $this->brands,
			'searchParams'	=> $this->searchParams
		))
		?>
		
		<div class="container">
			
			<style>
				.repo-language {
					float: right;
					font-style: italic;
				}

				.repo-name {
					font-weight: bold;
				}

				.repo-description {
					font-size: 14px;
				}

			</style>
			<?php
				$escaper = new Zend\Escaper\Escaper('utf-8');
				$image_baseurl = "http://akilia2.emdmusic.com/medias/products/dynamic/";
			?>
			<script type="text/javascript">
							$('#livesearch2').typeahead([
									
							{
								name: 'dataset_product_globalsearch',
								valueKey: 'reference',
								limit: 5,
								minLength: 1,
								header: '<h5 class="league-name">Products</h5>',
								remote: {
									url: '<?=
													$this->url('store/search', array(
														'action' => 'product'
															//'categories' => $category['reference'],
															//'page' => 1
															), array(), $reuseMatchedParams = true)
										?>?query=%QUERY',
									cache: true,
									timeout: 3000,
									filter: function(response) {
										//console.log('response', response);
										return response.data;
									}
								},
								template: [
									'<div>',
									'<div style=";">',
									'<img src="<?= $image_baseurl  ?>{{product_id}}-30x30_85.jpg" />',
									'<div style="float: right; style="width: 40px; height: 40px; overflow: hidden; border: 1px solid #E6E6E6; margin-right: 5px;>',
									'{{reference}}',	
									'</div>',
									'</div>',
									'</div>'
								].join(''),
								engine: Hogan
							}, {
								name: 'dataset_brand_globalsearch',
								valueKey: 'reference',
								limit: 5,
								minLength: 2,
								header: '<h5 class="league-name">Brands</h5>',
								remote: {
									url: '<?=
													$this->url('store/search', array(
														'action' => 'brand'
															//'categories' => $category['reference'],
															//'page' => 1
															), array(), $reuseMatchedParams = true)
										?>?query=%QUERY',
									cache: true,
									timeout: 3000,
									filter: function(response) {
										//console.log('response', response);
										return response.data;
									}
								},
								template: [
									'<div>',
									'{{title}}',	
									'</div>'
								].join(''),
								engine: Hogan
							
							}]
							
							).on('typeahead:selected', function(e, data, data_set) { 
								var new_location = '';
								if (data_set == 'dataset_brand_globalsearch') {
									var brand_reference = data.reference;
									new_location = '<?= $this->url('store/browse', array(), array(), false); ?>' + '/brands/' + brand_reference;
								} else if (data_set == 'dataset_product_globalsearch') {
									var product_id = data.product_id;
									new_location = '<?= $this->url('store/product', array('product_id' => ''), array(), false); ?>' +  product_id;
								}	
								if (new_location != '') {
									document.location.href = new_location;
								}
								return false;
							}
						);
			</script>
			<div class="container">
<?php echo $this->content; ?>		
			</div>	
			<footer>
				<p>&copy; Company 2013</p>
			</footer>
		</div>


	</body>
</html>
