---
Application\Entity\User:
  type: entity
  table: users  
  repositoryClass: Gedmo\Tree\Entity\Repository\NestedTreeRepository
  gedmo:
    tree:
      type: nested  
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
      options: 
        unsigned: true
  fields:
    password:
      type: string
      length: 32
    username:
      type: string
      length: 128
  indexes:
    search_idx:
      columns: username
      
Entity\Article:
  type: entity
  table: articles
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    title:
      type: string
      length: 64
    code:
      type: string
      length: 16
    slug:
      type: string
      length: 128
      gedmo:
        slug:
          separator: _
          style: camel
          fields:
            - title
            - code
  indexes:
    search_idx:
      columns: slug      