<div class="navbar navbar-default navbar-fixed-top">
	<div class="container">
        <div class="navbar-header">
			<a class="navbar-brand" href="./">Openstore</a>
			<button data-target="#navbar-main" data-toggle="collapse" type="button" class="navbar-toggle">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
        </div>
        <div id="navbar-main" class="navbar-collapse collapse">
			<ul class="nav navbar-nav">
				<li>
				<li><a href="#">Home</a></li>
				</li>
				<li class="active">

					<a href="<?=
					$this->url('store/browse', array(
						'page' => 1,
						'brands' => null,
						'filter' => null,
						'categories' => null,
						'query' => null
							), array(), $reuseMatchedParams = true);
					?>">Catalog
					</a>				
				</li>
				<li>
					<a href="<?=
					$this->url('shopcart', array(
						'page' => 1,
						'brands' => null,
						'filter' => null,
						'categories' => null,
						'query' => null
							), array(), $reuseMatchedParams = true);
					?>"">Shopcart</a>				
				</li>
				<li class="dropdown">
					<a id="themes" href="#" data-toggle="dropdown" class="dropdown-toggle">Themes <span class="caret"></span></a>
					<ul aria-labelledby="themes" class="dropdown-menu">
						<li><a href="./default/" tabindex="-1">Default</a></li>
						<li class="divider"></li>
						<li><a href="./amelia/" tabindex="-1">Amelia</a></li>
						<li><a href="./cerulean/" tabindex="-1">Cerulean</a></li>
						<li><a href="./cosmo/" tabindex="-1">Cosmo</a></li>
						<li><a href="./cyborg/" tabindex="-1">Cyborg</a></li>
						<li><a href="./flatly/" tabindex="-1">Flatly</a></li>
						<li><a href="./journal/" tabindex="-1">Journal</a></li>
						<li><a href="./readable/" tabindex="-1">Readable</a></li>
						<li><a href="./simplex/" tabindex="-1">Simplex</a></li>
						<li><a href="./slate/" tabindex="-1">Slate</a></li>
						<li><a href="./spacelab/" tabindex="-1">Spacelab</a></li>
						<li><a href="./united/" tabindex="-1">United</a></li>
					</ul>
				</li>

			</ul>

			<ul class="nav navbar-nav navbar-right">




				<?php if (!$this->zfcUserIdentity()): ?>
					<!-- display the login form -->
					<?php // echo $this->zfcUserLoginWidget(array('redirect' => 'store/browse')); ?>
					<a href="<?= $this->url('zfcuser/login') ?>" class="btn btn-primary navbar-btn">
						<?= $this->translate('Sign in') ?>
					</a>					
				<?php else: ?>
					<!-- display the 'display name' of the user -->
					<?php
					$name = $this->zfcUserIdentity()->getDisplayname();
					if ($name == '') {
						$name = $this->zfcUserIdentity()->getEmail();
					}
					?>
					<div class="btn-group">
					  <button type="button" class="btn btn-default  navbar-btn dropdown-toggle" data-toggle="dropdown">
						<?= $name ?> <span class="caret"></span>
					  </button>
					  <ul class="dropdown-menu" role="menu">
						<li><a>Text</a></li>
						<li class="divider"></li>
						<li><a href="<?= $this->url('zfcuser/logout') ?>"><?= $this->translate('Sign out') ?></a></li>
					  </ul>
					</div>					
					
				<?php endif ?>

				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">Language <b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li><a href="<?= $this->url(null, array('ui_language' => 'fr'), array(), $reuseMatchedParams = true) ?>">Français</a></li>
						<li><a href="<?= $this->url(null, array('ui_language' => 'en'), array(), $reuseMatchedParams = true) ?>">English</a></li>
						<li><a href="<?= $this->url(null, array('ui_language' => 'de'), array(), $reuseMatchedParams = true) ?>">German</a></li>
						<li><a href="<?= $this->url(null, array('ui_language' => 'nl'), array(), $reuseMatchedParams = true) ?>">Nederlands</a></li>
					</ul>
					</div>
				</li>

			</ul>


			<!--			
								<form class="navbar-form navbar-right" action="<?=
				$this->url('store/browse', array(
					'page' => 1,
					'brands' => null,
					'filter' => null,
					'categories' => null,
					'query' => null
						), array(), $reuseMatchedParams = true);
				?>" role="search" onsubmit="openstore_catalog_search()">
									<div class="form-group">
										<input class="twitter-typeahead form-control" type="text" id="livesearch2"  name="query" value="<?= $this->search_keywords ?>"  placeholder="Search">
									</div>
									<button type="submit" class="btn btn-default">Submit</button>
								</form>
			-->		

        </div>
	</div>
</div>		

