<?php
$theme_path = $this->basePath() . '/themes/webstore';
?>
<div class="carousel slide" id="myCarousel">
	<ol class="carousel-indicators">
		<li class="active" data-slide-to="0" data-target="#myCarousel"></li>
		<li data-slide-to="1" data-target="#myCarousel" class=""></li>
		<li data-slide-to="2" data-target="#myCarousel" class=""></li>
	</ol>
	<div class="carousel-inner">
		<div class="item active">
			<img alt="" src="<?php echo $theme_path . '/img/carousel_1.jpg' ?>">
			<div class="carousel-caption">
				<h4>First Thumbnail label</h4>
				<p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
			</div>
		</div>
		<div class="item">
			<img alt="" src="<?php echo $theme_path . '/img/carousel_2.jpg' ?>">
			<div class="carousel-caption">
				<h4>Second Thumbnail label</h4>
				<p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
			</div>
		</div>
		<div class="item">
			<img alt="" src="<?php echo $theme_path . '/img/carousel_3.jpg' ?>">
			<div class="carousel-caption">
				<h4>Third Thumbnail label</h4>
				<p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
			</div>
		</div>
	</div>

	<a data-slide="prev" href="#myCarousel" class="left carousel-control">‹</a>
	<a data-slide="next" href="#myCarousel" class="right carousel-control">›</a>
</div>


